### ISSUE TITLE
incoming.md - Force strict types on eval packet

### ISSUE THREAD

**Issue by CoderSudaWuda** [ABCxFF/diepindepth#1]
On 0x0d packet, im pretty sure when sending back 0x0b packet, format for the result is vu (at least how i encoded the packet).

**Comment by ABCxFF** [comment]
Though this may be the case for the current, in previous builds it allowed strings and integers, so its nice to show that it really could be anything. Especially if the "unknown" incoming 0x0C is still an eval packet that returns strings like it was previously, then the int only fact wouldn't be true. I'll add some more info demonstrating that in the future though
