### ISSUE TITLE
tankdefs.js

### ISSUE THREAD

**Issue by Auto-5** [ABCxFF/diepindepth#10]
No info about auto barrels for
- Auto 3
- Auto 5
- Auto Gunner
- Auto Trapper
- Auto Smasher

**Comment by ABCxFF** [comment]
Due to the weirdness of the game, auto barrels are stored in flags that change each update (the way they work changes). Check [here](https://github.com/ABCxFF/diepindepth/blob/15bf81abf9892330e93b297322b36d47d98fc821/memory/structs/TankDefinition.h#L57)
