### ISSUE TITLE
incoming.md - Building a party link

### ISSUE THREAD

**Issue by Auto-5** [ABCxFF/diepindepth#11]
https://github.com/ABCxFF/diepindepth/blob/main/protocol/incoming.md#building-a-party-link

```
stringNT("brlm") bytes(0x2D 0xCD 0x03 0x54 0xC3)

62 72 6C 6D 00 2D CD 03 54 C3
```

Where does `0x2D 0xCD 0x03 0x54 0xC3` come from?

**Comment by diepiodiscord** [comment]
The incoming 0x06 packet, which is generated by the server

**Comment by Auto-5** [comment]
I keep getting 403 status codes when connecting to the server, although the necessary headers were provided.

**Comment by diepiodiscord** [comment]
Can you connect to the server with a normal browser tab? The server may be closing or you might be IP banned

**Comment by ABCxFF** [comment]
Are you in the spike squad discord? We'd be able to help you out better there
