### ISSUE TITLE
Discussing XORs in update.md

### ISSUE THREAD

**Issue by ABCxFF** [ABCxFF/diepindepth#18]
No information about the xors is present. PRs welcome

**Comment by Craabby** [comment]
I'm not sure if the XORs should be in protocol/crypto.md or updates.md

**Comment by CantRunRiver** [comment]
hm

**Comment by ABCxFF** [comment]
updates.md, protocol should be for the shuffling i think

**Comment by Nul-led** [comment]
rip 😂
