### ISSUE TITLE
LAG

### ISSUE THREAD

**Issue by CoderSudaWuda** [ABCxFF/diepindepth#30]
Packet hook gives really bad lag (10fps + ~2000ms)

**Comment by diepiodiscord** [comment]
console.time() your packet handling code to make sure it's really the packet hook

**Comment by CoderSudaWuda** [comment]
it is, i tested only the packet hook by itself

**Comment by diepiodiscord** [comment]
I cannot replicate

**Comment by CoderSudaWuda** [comment]
I import the script via a repl (so it automatically updates), there wasn't an issue until today's update. Can you reproduce with this?
```js
// ==UserScript==
// @name         ABC Hook
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://diep.io/
// @icon         https://www.google.com/s2/favicons?domain=diep.io
// @require      https://raw.githubusercontent.com/Qwokka/wail.min.js/5e32d36bd7a5e0830d1ff4b64d3587aea13f77da/wail.min.js
// @require      https://wasm-hook-fetcher.codersudawuda.repl.co
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
})();
```

**Comment by ABCxFF** [comment]
Please stop opening off topic issues

**Comment by CoderSudaWuda** [comment]
how is this off topic?

**Comment by ABCxFF** [comment]
This isnt

**Comment by ABCxFF** [comment]
Oh wait lol. Crabby's automator is still running so there actually is an issue! LOL

**Comment by ABCxFF** [comment]
@CoderSudaWuda I am not experiencing this issue. How can I recreate the lag?

**Comment by ABCxFF** [comment]
If you had another memory related script installed, it might have made the packet hook script from hooking into the wrong function hence the lag - so maybe try running packet hook without any other scripts.

**Comment by Craabby** [comment]
Try looking at the performance tab

**Comment by diepiodiscord** [comment]
I could not reproduce with your repl version either

**Comment by ABCxFF** [comment]
@CoderSudaWuda `@require` meta tag is cached in most Script Monkey extensions. Your issue is likely that the PacketHook cached in your extension is not the latest version. You can test this with `PacketHook.CONFIG.BUILD === "b6c132517d2f9e84c9d9334a5fdeaba8a96e3343"` in your userscript you sent above. If it returns false then that is the issue - if it returns true however, you can re open this issue

**Comment by CoderSudaWuda** [comment]
there isnt a config property for Hook.

as for the questions above: i tested in an environment where its the only script, there is no other script clashing

**Comment by CoderSudaWuda** [comment]
i can't open the issue so uh can someone read this

**Comment by ABCxFF** [comment]
For `PacketHook` not `Hook`

**Comment by CoderSudaWuda** [comment]
yeah thats the issue, what do I do about it?

**Comment by ABCxFF** [comment]
Try `fetch()`ing the packet hook code yourself inside the script instead of depending on the tampermonkey/violentmonkey `@require`, that way it doesn't cache forever

**Comment by CoderSudaWuda** [comment]
CORS error, I can't do that. even if i could evalling doesnt work.

**Comment by Craabby** [comment]
that is an issue on your server, there is a cors package on npm

**Comment by CoderSudaWuda** [comment]
i can't fetch clientside

**Comment by ABCxFF** [comment]
Fetch to jsdelivr

**Comment by ABCxFF** [comment]
```js
fetch("https://cdn.jsdelivr.net/gh/ABCxFF/diepindepth/protocol/userscripts/packethook.user.js?" + Date.now())
```

**Comment by Craabby** [comment]
you could always make your own wasm hook and have it fetch the constants from an automator inside the hijacked WebAssembly.instatiate

**Comment by CoderSudaWuda** [comment]
the thing with fetching is that i can't import anything from it since evalling it wont work

**Comment by ABCxFF** [comment]
Maybe eval the config only? There should be a way, good luck on your scripting!

**Comment by CoderSudaWuda** [comment]
is there a way to import WAIL without using @require

**Comment by CoderSudaWuda** [comment]
ok i got around it!
```js
    const resp = await fetch("https://cdn.jsdelivr.net/gh/ABCxFF/diepindepth/protocol/userscripts/packethook.user.js?" + Date.now());
    const js = await resp.text();

    const resp2 = await fetch('https://raw.githubusercontent.com/Qwokka/wail.min.js/5e32d36bd7a5e0830d1ff4b64d3587aea13f77da/wail.min.js');
    const js2 = await resp2.text();

    var script1 = document.createElement('script');
    script1.appendChild(document.createTextNode(js2));
    document.head.appendChild(script1);

    var script = document.createElement('script');
    script.appendChild(document.createTextNode(js));
    document.head.appendChild(script);
```

**Comment by diepiodiscord** [comment]
GM_xmlhttpRequest bypasses CORS
