### ISSUE TITLE
Modifying packet before sending

### ISSUE THREAD

**Issue by CoderSudaWuda** [ABCxFF/diepindepth#33]
I tried editing data in the serverbkund event but it sends the same way as it was supposed to be done.

**Comment by Nul-led** [comment]
well that is to be expected. u dont actually edit the memory, more like a "copy" of the original packet data. if you were to edit the memory directly u have to ensure that the packet stays the same length.

**Comment by CoderSudaWuda** [comment]
Is there a way to edit packets before sending? I need to edit the init packet.

**Comment by Nul-led** [comment]
well there are ways. i even described one in my last comment.

**Comment by ABCxFF** [comment]
How are you modifying it @CoderSudaWuda?

**Comment by ABCxFF** [comment]
In theory we could switch the `.slice` to `.subarray` that way anyone can modify any packet from within the event instead of having to modify the packet hook.

**Comment by CoderSudaWuda** [comment]
Im trying to modify the player token sent to server

**Comment by Nul-led** [comment]
but then again, u cant modify its length without reallocating new space for the modified packet rendering this literally useless.

**Comment by CoderSudaWuda** [comment]
Does the packet hook check when a packet is sending? Because if it isnt sent, then i can return on my ws hook, send a new 0x00 packet, then continue ws sending

**Comment by CoderSudaWuda** [comment]
Then maybe somehow add a feature to make it like an actual hook, where you can send a new uint8array based off of what data is

**Comment by Nul-led** [comment]
well u can prevent the packet from being sent by returning true

**Comment by CoderSudaWuda** [comment]
can i not just do

```js
// in the event
data = new Uint8Array(...)

**Comment by CoderSudaWuda** [comment]
@ABCxFF is there any way that you can change your script to change the buffer by setting data to a new buffer a n d then send that instead of original buffer

**Comment by Nul-led** [comment]
if you simply set this without allocating new memory u might overwrite important data

**Comment by Nul-led** [comment]
also, since u wanted to research whats happens if you change the player token:
u get disconnected. thats it. and after a couple of tries u get a short timeout.

**Comment by CoderSudaWuda** [comment]
ik something you dont and ill use it to my advabtage

**Comment by CoderSudaWuda** [comment]
Wait @Nul-led @ABCxFF can i not just do

```js
window.addEventListener("serverbound", function(data) {
     data = new Uint8Array(data);
     if (data[0] === 0x00) {
          Hook.send(new Uint8Array(...));
          return true;
     }
});
```

**Comment by ABCxFF** [comment]
@CoderSudaWuda No, and i will not be changing `.subarray` to `slice` anytime sooner.
```js
let sendingArtificial = false;
const Hook = window.Hook = new PacketHook(function(type, ptr, len) {
  const packet = Hook.HEAPU8.slice(ptr, ptr + len);
  const typeCode = TYPE[type];

  if (typeCode === "serverbound" && packet[0] === 0x00 && !sendingArtificial) {
     sendingArtificial = true;
     Hook.send([0x00, ...]);
     sendingArtificial = false;
     return 1;
  }
  return 0;
});
```
